### ISSUE TITLE
[bug] Screen height is deprecated

### ISSUE THREAD

**Issue by epsilon-0** [nwg-piotr/azote#108] opened 2020-09-12 12:24 UTC
**Describe the bug**
when running `azote` from command line, I get a warning
```
main.py:746: DeprecationWarning: Gdk.Screen.height is deprecated
  h = screen.height()
```

**To Reproduce**
Start `azote` from command line

**Expected behavior**
No warning

**Desktop (please complete the following information):**
 - Linux distribution: Gentoo
 - WM: Wayfire

**Azote version (please state it clearly if you use -git version):**
- 1.7.14

**Comment by nwg-piotr** [comment] 2020-09-12 14:02
LOL, it's not a bug, it's a feature. ;)

Seriously: Azote detects screens in several ways, according to the environment. This warning should be harmless, but now I realize that this part of code does not have to be used on Wayland. I'll try to resolve it sooner or later, but it should not stop Azote from working, does it?

**Comment by epsilon-0** [comment] 2020-09-12 14:06
No worries, I'll let this be open as a shameful reminder for the disappointment that you are to your ancestors :stuck_out_tongue: .
But feel free to close if you like, or close when its resolved, any is fine.

**Comment by epsilon-0** [comment] 2020-09-12 14:09
> LOL, it's not a bug, it's a feature. ;)
> 
> Seriously: Azote detects screens in several ways, according to the environment. This warning should be harmless, but now I realize that this part of code does not have to be used on Wayland. I'll try to resolve it sooner or later, but it should not stop Azote from working, does it?

Kind of does. All images are stretched, no matter if tile/center.

**Comment by nwg-piotr** [comment] 2020-09-12 14:21
Well, can't confirm...

![image](https://user-images.githubusercontent.com/20579136/92997491-f877b580-f513-11ea-9187-f7c36efdbc18.png)

**Comment by epsilon-0** [comment] 2020-09-12 14:29
I will try to see what is happening. Thanks!

**Comment by nwg-piotr** [comment] 2020-09-12 14:33
As I felt mentally trapped in between C++ and python, I decided to have a brake with Imperial Stout, so I won't even touch the code at the moment. Feel free to open an issue if you confirm any scaling issues.

**Comment by nwg-piotr** [comment] 2020-09-12 14:55
By the way: Azote was designed with primarily multi-headed setups in mind. That's what it looks like on my machine:

![image](https://user-images.githubusercontent.com/20579136/92998166-9c636000-f518-11ea-80f5-a76aa521b775.png)

**Comment by nwg-piotr** [comment] 2020-09-26 22:45
Resolved in slightly tricky way.

**Closed by nwg-piotr** 2020-09-26 22:45 UTC

**Comment by epsilon-0** [comment] 2020-09-26 22:47
:D 
Nice, thanks!
